# Generated by Django 5.2.15 on 2026-06-13 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, max_length=80)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicine_links', to='api.ingredient')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_links', to='api.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='ingredients',
            field=models.ManyToManyField(related_name='medicines', through='api.MedicineIngredient', to='api.ingredient'),
        ),
        migrations.CreateModel(
            name='IngredientNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('positive', '필요 (보충 권장)'), ('caution', '주의 (제한 권장)')], max_length=10)),
                ('weight', models.FloatField(default=1.0)),
                ('note', models.TextField(blank=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_links', to='api.ingredient')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_links', to='api.nutrient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutrients',
            field=models.ManyToManyField(related_name='ingredients', through='api.IngredientNutrient', to='api.nutrient'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_instruction', models.CharField(blank=True, max_length=200)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='api.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.ManyToManyField(related_name='prescriptions', through='api.PrescriptionItem', to='api.medicine'),
        ),
        migrations.AddConstraint(
            model_name='medicineingredient',
            constraint=models.UniqueConstraint(fields=('medicine', 'ingredient'), name='uniq_medicine_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='ingredientnutrient',
            constraint=models.UniqueConstraint(fields=('ingredient', 'nutrient', 'effect'), name='uniq_ingredient_nutrient_effect'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.UniqueConstraint(fields=('prescription', 'medicine'), name='uniq_prescription_medicine'),
        ),
    ]
