# Generated by Django 5.2.15 on 2026-06-13 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='hira', max_length=40)),
                ('raw_precautions', models.JSONField(default=list)),
                ('refined', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caution', to='api.medicine')),
            ],
        ),
    ]
